### ISSUE TITLE
Creating Pages and Documentation

### ISSUE THREAD

**Issue by gmarokov** [softlion/NotionSharp#1]
Hi creators, 

Is Creating pages available in the API? I haven't found any information in the code neither in the docs. Do you also provide some kind of extended documentation for the API? 

Regards

**Comment by softlion** [comment]
Hello g,
The current version is using the private api, and is read only.
Regards

**Comment by gmarokov** [comment]
Can eloborate more on what private api means? Do you have plans to use the public api and add Page Creation? 
Regards

**Comment by softlion** [comment]
Yes i have plan to migrate that to the public API now that it's available. With the full API support. You want to help ?

**Comment by gmarokov** [comment]
I can help. Do you have a plan how to do the migration? As far as I see its quite different than the public api.

**Comment by softlion** [comment]
@gmarokov #2

**Comment by softlion** [comment]
Ok so, if you look at NotionSharp.ApiClient.Tests, it contains unit tests for nearly all read API endpoints.  
It is missing:
- page: create/update
- block: append
- database: all api

Would you like to dev one of these ?

**Comment by gmarokov** [comment]
Hey @softlion, sorry I was tight on time, but yes I can help with some of them. Do you want to switch conversation in the other issue? I was thinking about the Authorization and if we can figure out the authorization in the client?

**Comment by softlion** [comment]
There does not seem to be any possibility to make that work automatically so if you figure out a trick go For it !
